### ISSUE TITLE
How to use this library in ES6 import or require?

### ISSUE THREAD

**Issue by che5ya** [sankalpkataria/search-in-file#13]
how to use this library in vue.js es6?
i used this library in js, but it doesn't work. 
It was not possible to use library via import or require!

**Comment by sankalpkataria** [comment]
Hi @che5ya ,
This library cannot be used with vue.js or any frontend framework/library.
This only works with nodeJs.

Reason:
Javascript cannot access file system. It was never meant to do that.
Node js on other hand has `fs` module which is built using C/C++(which can access file system) and compiled using tools that converts it into something which can be used in JS (This process is known as binding)

**Comment by che5ya** [comment]
oh i see. @sankalpkataria 
I thought it would work if the source code converted to string of file was inserted into "data" in search() of this library.

thank you for your answer.
