### ISSUE TITLE
How to use in nodeJS

### ISSUE THREAD

**Issue by HassanElDessouki** [sankalpkataria/search-in-file#14]
Hi!
I don't really understand how to use this module in nodeJS, can you please help?
I would like to search a folder containing *.txt files for a specific string.

Thanks

**Comment by sankalpkataria** [comment]
Hi, 

The modules exports a function named `fileSearch` which can be used as follows

```
fileSearch(<array of paths>, <string to search>, {
  fileMask: 'txt',
    //   other options depending on requirement
})
```

**example**:

```
fileSearch(['./src/config'], 'export', {
  fileMask: 'ts',
  ignoreCase: true,
  recursive: true,
  searchResults: 'lineNo',
})
```

Let me know if you still face any issue, I'll be happy to help.

**Comment by HassanElDessouki** [comment]
Hello @sankalpkataria 
Thanks for your reply and help!

I've added a require statement for search-in-file as follows:
`
var fileSearch = require('search-in-file');
`



and then added your example, I'm getting 'TypeError: fileSearch is not a function'

I'm pretty sure I'm doing something wrong, but I don't know it. Your help here is highly appreciated.

Thanks!

**Comment by HassanElDessouki** [comment]
I think I understand now,
`var search = require('search-in-file');`

```
search.fileSearch(['./testing/'], 'export', {
  fileMask: 'txt',
  ignoreCase: true,
  recursive: true,
  searchResults: 'lineNo',
})
```

Running it this way stopped my errors, but, I get no output!

**Comment by sankalpkataria** [comment]
Could you please share a screenshot of your folder structure? And the contents of the file(just the part where the word export is) which was expected in the results.

I am guessing that the word `export` might not be present in any of the `txt` files.

**Comment by sankalpkataria** [comment]
If you face any problems, feel free to reopen the issue, I'll be happy to help.
